version: "3.9"
services:

  db:
    image: mysql
    container_name: mma_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mma
      MYSQL_DATABASE: mma
    ports:
      - "3310:3311"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project_network

  app:
    image: openjdk:21-jdk-slim
    working_dir: /app
    volumes:
      - ./target/ProjectEventFight-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8085:8086"
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - db
    networks:
      - project_network

volumes:
  db_data:

networks:
  project_network:
    driver: bridge
